### ISSUE TITLE
feat: Dinner table

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1058]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/90652907-8942d480-e279-11ea-84ab-cc3f2131230d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/dinner-table.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by CaioTsubake** [comment]
I would like to tackle this issue, please.

**Comment by CaioTsubake** [comment]
Funny. When I run the command 

> npm run start

I get the following error:
```
> @ start C:\Users\caiot\Documents\Profissional\Projetos\GameOfLife\Test\game-of-life
> nodemon scripts/prebuild & webpack-dev-server --config scripts/webpack.config.js

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node scripts/prebuild.js`
C:\Users\caiot\Documents\Profissional\Projetos\GameOfLife\Test\game-of-life\node_modules\fs-extra\lib\mkdirs\make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\caiot\Documents\Profissional\Projetos\GameOfLife\Test\game-of-life\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
[nodemon] app crashed - waiting for file changes before starting...
```
I am running Node 8.11.2 and NPM 5.6.0

Tried cloning the project again, but same issue. Is there something I am doing wrong? 
Sorry if here is not the correct place to ask this question.

**Comment by TroyTae** [comment]
`fs-extra` needs 10 or higher nodejs version.
Can you update it and retry again?

**Comment by CaioTsubake** [comment]
Thanks. Did that and it works:
```
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node scripts/prebuild.js`
[nodemon] clean exit - waiting for changes before restart
```
I still cannot get to run on `locahost:4200`. It says it cannot connect
I tested the model on a simulator instead.

**Comment by CaioTsubake** [comment]
Your welcome.
Thanks for the project. It's a great place to start.
